name: ikon

on:
  push:
    tags:
      - 'v*.*.*-ikon*'

jobs:
  windows-2022:
    name: windows-2022
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.*
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.*
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - name: Run './build.cmd InstallDependencies Compile Test Pack'
        run: ./build.cmd InstallDependencies Compile Test Pack
      - name: 'Publish: NuGet Packages'
        uses: actions/upload-artifact@v4
        with:
          name: NuGet Packages
          path: artifacts/*.nupkg
